module.exports = {
  SECRET: process.env.SECRET,
  PORT: process.env.PORT,
  DB_URL: process.env.DB_URL,

  CONFIRM_EMAIL_USER: process.env.CONFIRM_MAIL_USER,
  CONFIRM_EMAIL_PASS: process.env.CONFIRM_MAIL_PASS,
  
  SEED_TIME_NORTHERN: process.env.SEED_TIME_NORTHERN,
  SEED_TIME_VIP_HOCHIMINH: process.env.SEED_TIME_VIP_HOCHIMINH,
  SEED_TIME_VIP_HANOI: process.env.SEED_TIME_VIP_HANOI,
  SEED_TIME_VIP_SAIGON: process.env.SEED_TIME_VIP_SAIGON,
  SEED_TIME_SOUTHERN_HOCHIMINH: process.env.SEED_TIME_SOUTHERN_HOCHIMINH,
  SEED_TIME_CENTRAL_QUANGNAM: process.env.SEED_TIME_CENTRAL_QUANGNAM,

  RESULT_URL1: process.env.RESULT_URL1,
  RESULT_URL2: process.env.RESULT_URL2,
  RESULT_URL_NORTHERN: process.env.RESULT_URL_NORTHERN,
  RESULT_URL_SOUTHERN: process.env.RESULT_URL_SOUTHERN,
  RESULT_URL_ASEAN: process.env.RESULT_URL_ASEAN,

  SERVICE_URL: process.env.SERVICE_URL_DEBUG
};